force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <label>Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>Rent</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resident</label>
    <referenceTo>Resident__c</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resident__c/Resident__c.object-meta.xml
<CustomObject>
    <label>Resident</label>
    <nameField>
        <label>Resident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resident__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resident__c/fields/Lease__c.field-meta.xml
<CustomField>
    <fullName>Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lease</label>
    <referenceTo>Lease__c</referenceTo>
    <relationshipLabel>Residents</relationshipLabel>
    <relationshipName>Residents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Residents.cls
public class Residents {
    

    
    @AuraEnabled
    public static List<ID> getResidents(){
            String userFN = Userinfo.getFirstName();
    		String userLN = Userinfo.getLastName();
        if(!Schema.SObjectType.Resident__c.isAccessible()){
            throw new AuraHandledException('You need to be a resident to access this page');
        }
        List<Resident__c> residents= [SELECT ID FROM Resident__c WHERE First_Name__c = :userFn LIMIT 1];
        List<ID> ids = new List<ID>();
          for (Resident__c res : residents) {
      		ids.add(res.ID);
    }
        return ids;
    }
    
    
    public Resident__c res {get{
        	String userFN = Userinfo.getFirstName();
    		String userLN = Userinfo.getLastName();
        return [SELECT First_Name__c, Last_Name__c, Lease__r.Name, Lease__r.Start_Date__c,
                                        Lease__r.End_Date__c, Lease__r.Rent__c FROM Resident__c WHERE First_Name__c = :userFN 
                                       AND Last_Name__c = :userLN LIMIT 1];}}
	
}